name: Zig Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      - name: Setup elan toolchain
        # if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          chmod u+x elan-init.sh
          ./elan-init.sh -y --default-toolchain leanprover/lean4:nightly
          echo "Adding location $HOME/.elan/bin to PATH..."
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      # - name: Setup elan toolchain on Windows
      #   if: matrix.os == 'windows-latest'
      #   shell: pwsh
      #   run: |
      #     curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1
      #     .\elan-init.ps1 -NoPrompt 1 -DefaultToolchain leanprover/lean4:nightly
      #     echo "Adding location $HOME\.elan\bin to PATH..."
      #     echo "$HOME\.elan\bin" >> $env:GITHUB_PATH

      - name: Build Summary ${{ matrix.targets }}
        run: zig build --summary all -freference-trace

      - name: Running FFI ${{ matrix.targets }}
        run: zig build zffi --summary all -freference-trace

      - name: Running Reverse-FFI ${{ matrix.targets }}
        run: zig build rffi -freference-trace